version: '3' 

services:
    
  web: 
    build: ./docker-config/php
    volumes:
      - ./src:/var/www/src
      - ./docker-config/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
    # restart: always

  nginx:
    image: nginx
    build: ./docker-config/nginx
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/src
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    # restart: always

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: main
      TZ: "Asia/Tokyo"
    ports:
      - 54320:5432 #SQLと違うので注意
    volumes:
      - ./docker-config/postgres/data:/var/lib/postgresql/data
      - ./docker-config/postgres/logs:/var/log
    # restart: always